FROM node:20-alpine AS build

WORKDIR /app

ARG VITE_AGENT_API_BASE_URL=""
ARG VITE_AGENT_SITE_ID="lecrowndevelopment.com"
ARG VITE_AGENT_BOT_ID="benjamin-lagrone"
ARG VITE_PORTAL_DISABLE_AUTH="true"
ARG VITE_PORTAL_KEYCLOAK_URL="https://auth.pericopeai.com"
ARG VITE_PORTAL_KEYCLOAK_REALM="lecrown-portal"
ARG VITE_PORTAL_KEYCLOAK_CLIENT_ID="lecrown-portal-web"
ARG VITE_PORTAL_DEFAULT_PROJECT_ID="northstar-automation"
ARG VITE_PORTAL_DEV_EMAIL="admin@lecrowndevelopment.com"
ARG VITE_PORTAL_DEV_NAME="Local Portal Admin"

ENV VITE_AGENT_API_BASE_URL=$VITE_AGENT_API_BASE_URL
ENV VITE_AGENT_SITE_ID=$VITE_AGENT_SITE_ID
ENV VITE_AGENT_BOT_ID=$VITE_AGENT_BOT_ID
ENV VITE_PORTAL_DISABLE_AUTH=$VITE_PORTAL_DISABLE_AUTH
ENV VITE_PORTAL_KEYCLOAK_URL=$VITE_PORTAL_KEYCLOAK_URL
ENV VITE_PORTAL_KEYCLOAK_REALM=$VITE_PORTAL_KEYCLOAK_REALM
ENV VITE_PORTAL_KEYCLOAK_CLIENT_ID=$VITE_PORTAL_KEYCLOAK_CLIENT_ID
ENV VITE_PORTAL_DEFAULT_PROJECT_ID=$VITE_PORTAL_DEFAULT_PROJECT_ID
ENV VITE_PORTAL_DEV_EMAIL=$VITE_PORTAL_DEV_EMAIL
ENV VITE_PORTAL_DEV_NAME=$VITE_PORTAL_DEV_NAME

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \
  CMD wget -qO- http://127.0.0.1:8080/ >/dev/null || exit 1
